import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins=Poppins({
  subsets:['latin'], 
  weight:['500'],})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Provider>
          {children}
        </Provider>
        <Toaster/>
      </body>
    </html>
    </ClerkProvider>
  );
}
